name: Actualizador de Cotizaciones VXL Economía

on:
  schedule:
    - cron: '* * * * *' # Ejecución cada 1 minuto
  workflow_dispatch:

# PERMISO OBLIGATORIO PARA EVITAR EL EXIT CODE 128 (PERMITIR PUSH EN EL REPO)
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del Repositorio
        uses: actions/checkout@v4 # Actualizado a v4 para corregir warning de Node.js

      - name: Configurar Node.js
        uses: actions/setup-node@v4 # Actualizado a v4
        with:
          node-version: '20'

      - name: Ejecutar Script de Actualización
        run: node ./scripts/update-quotes.js

      - name: Commit y Push a GitHub
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ./data/quotes.json
          git diff-index --quiet HEAD || (git commit -m 'Auto-update: cotizaciones cada 1 min [skip ci]' && git push)
